#Targetnamen : dependencies
#<TAB>command

all:addrecord.c deleterecord.c gotoxy.c listrecord.c modifyrecord.c 
    gcc addrecord.c deleterecord.c gotoxy.c listrecord.c modifyrecord.c - o all.exe

	run: all
	./all.exe